#!/bin/sh

current_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_path="$(dirname "$current_dir")"
repo_name="$(basename "$repo_path" .git)"
script_path="/data"

while read oldrev newrev ref
do
    python3 $script_path/send-commit.py $repo_name $repo_path $ref $oldrev $newrev
done
